# Generated by Django 5.1.4 on 2026-05-11 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites_config', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=255)),
                ('language', models.CharField(choices=[('en', 'English'), ('ja', 'Japanese'), ('ne', 'Nepali')], db_index=True, max_length=5)),
                ('value', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(blank=True, help_text='Leave blank for a global/default translation', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='sites_config.country')),
            ],
            options={
                'verbose_name': 'Translation',
                'verbose_name_plural': 'Translations',
                'ordering': ['key', 'language'],
                'unique_together': {('key', 'language', 'country')},
            },
        ),
    ]
