# Generated by Django 5.1.4 on 2026-05-11 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites_config', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanguageCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(help_text='e.g. Japanese, English, Nepali', max_length=100)),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('elementary', 'Elementary'), ('intermediate', 'Intermediate'), ('upper_intermediate', 'Upper Intermediate'), ('advanced', 'Advanced')], max_length=30)),
                ('level_code', models.CharField(blank=True, help_text='e.g. N5, N4, N3, N2, N1 for Japanese', max_length=20)),
                ('title_en', models.CharField(max_length=200)),
                ('title_ja', models.CharField(blank=True, max_length=200)),
                ('title_ne', models.CharField(blank=True, max_length=200)),
                ('description_en', models.TextField(blank=True)),
                ('description_ja', models.TextField(blank=True)),
                ('description_ne', models.TextField(blank=True)),
                ('duration_weeks', models.PositiveIntegerField(blank=True, null=True)),
                ('schedule', models.CharField(blank=True, help_text='e.g. Weekdays 9am–12pm', max_length=200)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='JPY', max_length=5)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='sites_config.country')),
            ],
            options={
                'verbose_name': 'Language Course',
                'verbose_name_plural': 'Language Courses',
                'ordering': ['order', 'level'],
            },
        ),
        migrations.CreateModel(
            name='NewsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('news', 'News'), ('event', 'Event')], default='news', max_length=10)),
                ('title_en', models.CharField(max_length=300)),
                ('title_ja', models.CharField(blank=True, max_length=300)),
                ('title_ne', models.CharField(blank=True, max_length=300)),
                ('excerpt_en', models.TextField(blank=True, max_length=500)),
                ('excerpt_ja', models.TextField(blank=True, max_length=500)),
                ('excerpt_ne', models.TextField(blank=True, max_length=500)),
                ('body_en', models.TextField(blank=True)),
                ('body_ja', models.TextField(blank=True)),
                ('body_ne', models.TextField(blank=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='news/')),
                ('event_date', models.DateTimeField(blank=True, help_text='For events: when it takes place', null=True)),
                ('event_location', models.CharField(blank=True, max_length=300)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('slug', models.SlugField(max_length=300, unique=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_events', to='sites_config.country')),
            ],
            options={
                'verbose_name': 'News / Event',
                'verbose_name_plural': 'News & Events',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='globe', help_text="Icon name e.g. 'globe', 'book', 'file-text', 'star'", max_length=100)),
                ('title_en', models.CharField(max_length=200)),
                ('title_ja', models.CharField(blank=True, max_length=200)),
                ('title_ne', models.CharField(blank=True, max_length=200)),
                ('description_en', models.TextField()),
                ('description_ja', models.TextField(blank=True)),
                ('description_ne', models.TextField(blank=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='sites_config.country')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text='e.g. 500+, 10, 98%', max_length=20)),
                ('label_en', models.CharField(max_length=100)),
                ('label_ja', models.CharField(blank=True, max_length=100)),
                ('label_ne', models.CharField(blank=True, max_length=100)),
                ('icon', models.CharField(default='users', max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='sites_config.country')),
            ],
            options={
                'verbose_name': 'Site Stat',
                'verbose_name_plural': 'Site Stats',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('role_en', models.CharField(max_length=200)),
                ('role_ja', models.CharField(blank=True, max_length=200)),
                ('role_ne', models.CharField(blank=True, max_length=200)),
                ('bio_en', models.TextField(blank=True)),
                ('bio_ja', models.TextField(blank=True)),
                ('bio_ne', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='team/')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('linkedin', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='sites_config.country')),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=200)),
                ('student_photo', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
                ('origin_country', models.CharField(blank=True, help_text="Student's home country e.g. Nepal, Vietnam", max_length=100)),
                ('destination', models.CharField(blank=True, help_text='e.g. Waseda University, Japan', max_length=200)),
                ('rating', models.PositiveSmallIntegerField(default=5, help_text='1–5 stars')),
                ('quote_en', models.TextField()),
                ('quote_ja', models.TextField(blank=True)),
                ('quote_ne', models.TextField(blank=True)),
                ('service_used', models.CharField(blank=True, help_text='e.g. Study Abroad, JLPT Preparation', max_length=200)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='sites_config.country')),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
    ]
