# Generated by Django 5.1.4 on 2026-05-13 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='languagecourse',
            name='price_ja',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='languagecourse',
            name='price_ne',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='languagecourse',
            name='schedule_ja',
            field=models.CharField(blank=True, help_text='例: 平日 午前9時〜午後12時', max_length=200),
        ),
        migrations.AddField(
            model_name='languagecourse',
            name='schedule_ne',
            field=models.CharField(blank=True, help_text='उदाहरण: कार्यदिवस बिहान ९ बजे–१२ बजे', max_length=200),
        ),
        migrations.AddField(
            model_name='newsevent',
            name='event_location_ja',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='newsevent',
            name='event_location_ne',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='sitestat',
            name='value_ja',
            field=models.CharField(default='500+', help_text='例: 500+, 10, 98%', max_length=20),
        ),
        migrations.AddField(
            model_name='sitestat',
            name='value_ne',
            field=models.CharField(default='५००+', help_text='उदाहरण: ५००+, १०, ९८%', max_length=20),
        ),
        migrations.AddField(
            model_name='teammember',
            name='name_ja',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='teammember',
            name='name_ne',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='destination_ja',
            field=models.CharField(blank=True, help_text='例：早稲田大学（日本）', max_length=200),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='origin_country_ja',
            field=models.CharField(blank=True, help_text='学生の母国（例：ネパール、ベトナム）', max_length=100),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='origin_country_ne',
            field=models.CharField(blank=True, help_text='विद्यार्थीको गृह देश (जस्तै: नेपाल, भियतनाम)', max_length=100),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='service_used_ja',
            field=models.CharField(blank=True, help_text='例: 留学、JLPT対策', max_length=200),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='service_used_ne',
            field=models.CharField(blank=True, help_text='उदाहरण: विदेश अध्ययन, JLPT तयारी', max_length=200),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='student_name_ja',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='student_name_ne',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='sitestat',
            name='value',
            field=models.CharField(default='500+', help_text='e.g. 500+, 10, 98%', max_length=20),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='destination',
            field=models.CharField(blank=True, help_text='उदाहरण: वासेदा विश्वविद्यालय, जापान', max_length=200),
        ),
    ]
