# Generated by Django 5.1.4 on 2026-05-13 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_languagecourse_price_ja_languagecourse_price_ne_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='destination_ne',
            field=models.CharField(blank=True, help_text='उदाहरण: वासेदा विश्वविद्यालय, जापान', max_length=200),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='destination',
            field=models.CharField(blank=True, help_text='e.g. Waseda University, Japan', max_length=200),
        ),
    ]
