# Generated by Django 5.1.4 on 2026-05-14 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_testimonial_destination_ne_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsevent',
            name='google_maps_url',
            field=models.URLField(blank=True),
        ),
    ]
