# Generated by Django 5.1.4 on 2026-05-11 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='e.g. JP, NP, AU', max_length=4, unique=True)),
                ('name', models.CharField(help_text='e.g. Japan', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('default_language', models.CharField(choices=[('en', 'English'), ('ja', 'Japanese'), ('ne', 'Nepali')], default='en', max_length=5)),
                ('locale', models.CharField(default='en-US', help_text='BCP-47 locale used for date/number formatting, e.g. ja-JP', max_length=10)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order in country switcher')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='NavItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_en', models.CharField(max_length=100, verbose_name='Label (English)')),
                ('label_ja', models.CharField(blank=True, max_length=100, verbose_name='Label (Japanese)')),
                ('label_ne', models.CharField(blank=True, max_length=100, verbose_name='Label (Nepali)')),
                ('url', models.CharField(help_text='e.g. / or /about or https://...', max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('open_in_new_tab', models.BooleanField(default=False)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nav_items', to='sites_config.country')),
            ],
            options={
                'verbose_name': 'Nav Item',
                'verbose_name_plural': 'Nav Items',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=200)),
                ('tagline', models.CharField(blank=True, max_length=300)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='favicons/')),
                ('color_primary', models.CharField(default='#0ea5e9', help_text='Hex color, e.g. #0ea5e9', max_length=7)),
                ('color_secondary', models.CharField(default='#64748b', max_length=7)),
                ('color_accent', models.CharField(default='#f59e0b', max_length=7)),
                ('color_bg', models.CharField(default='#ffffff', max_length=7, verbose_name='Background color')),
                ('color_text', models.CharField(default='#1e293b', max_length=7, verbose_name='Text color')),
                ('color_navbar_bg', models.CharField(default='#ffffff', max_length=7, verbose_name='Navbar background')),
                ('color_navbar_text', models.CharField(default='#1e293b', max_length=7, verbose_name='Navbar text')),
                ('font_primary', models.CharField(default='Noto Sans JP', help_text='Google Fonts name, e.g. Noto Sans JP', max_length=100)),
                ('font_heading', models.CharField(default='Noto Sans JP', max_length=100)),
                ('address_line1', models.CharField(blank=True, max_length=200)),
                ('address_line2', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('google_maps_embed_url', models.TextField(blank=True, help_text='Paste the full Google Maps embed iframe src URL')),
                ('google_maps_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('google_maps_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('sns_facebook', models.URLField(blank=True)),
                ('sns_instagram', models.URLField(blank=True)),
                ('sns_twitter', models.URLField(blank=True, verbose_name='Twitter / X')),
                ('sns_youtube', models.URLField(blank=True)),
                ('sns_line', models.URLField(blank=True, verbose_name='LINE (Japan)')),
                ('sns_linkedin', models.URLField(blank=True)),
                ('sns_tiktok', models.URLField(blank=True)),
                ('footer_text', models.TextField(blank=True)),
                ('copyright_text', models.CharField(blank=True, max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config', to='sites_config.country')),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configurations',
            },
        ),
    ]
