# Generated by Django 5.1.4 on 2026-05-11 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites_config', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='hero_bg_image',
            field=models.ImageField(blank=True, null=True, upload_to='hero/'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='sns_whatsapp',
            field=models.URLField(blank=True),
        ),
    ]
