# Generated by Django 5.1.4 on 2026-05-12 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites_config', '0002_siteconfig_hero_bg_image_siteconfig_sns_whatsapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfig',
            name='sns_whatsapp',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
