# Generated by Django 5.1.4 on 2026-05-13 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites_config', '0003_alter_siteconfig_sns_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='address_line1_ja',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='address_line1_ne',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='address_line2_ja',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='address_line2_ne',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='city_ja',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='city_ne',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='copyright_text_ja',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='copyright_text_ne',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='footer_text_ja',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='footer_text_ne',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='site_name_ja',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='site_name_ne',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='tagline_ja',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='tagline_ne',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
