# Generated by Django 5.1.4 on 2026-05-15 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites_config', '0004_siteconfig_address_line1_ja_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='Canonical domain e.g. https://www.3staredu.jp'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='google_analytics_id',
            field=models.CharField(blank=True, help_text='Google Analytics 4 Measurement ID e.g. G-XXXXXXXXXX', max_length=30),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='meta_description',
            field=models.TextField(blank=True, help_text='Google search snippet (max 155 chars recommended)', max_length=160),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Browser tab title / Google title (max 60 chars recommended)', max_length=70),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='og_image',
            field=models.ImageField(blank=True, help_text='Open Graph image shown when sharing on social media (1200×630px recommended)', null=True, upload_to='seo/'),
        ),
    ]
