# Generated by Django 5.1.4 on 2026-05-15 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites_config', '0005_siteconfig_canonical_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('image', 'Image'), ('youtube', 'YouTube Video'), ('vimeo', 'Vimeo Video'), ('video', 'Direct Video File')], default='image', max_length=10)),
                ('file', models.FileField(blank=True, help_text='Upload image or video file', null=True, upload_to='gallery/')),
                ('thumbnail', models.ImageField(blank=True, help_text='Thumbnail for video items (optional — auto-generated for YouTube)', null=True, upload_to='gallery/thumbnails/')),
                ('video_url', models.URLField(blank=True, help_text='YouTube or Vimeo URL e.g. https://www.youtube.com/watch?v=XXXX')),
                ('title_en', models.CharField(blank=True, max_length=300)),
                ('title_ja', models.CharField(blank=True, max_length=300)),
                ('title_ne', models.CharField(blank=True, max_length=300)),
                ('caption_en', models.TextField(blank=True)),
                ('caption_ja', models.TextField(blank=True)),
                ('caption_ne', models.TextField(blank=True)),
                ('tags', models.CharField(blank=True, help_text="Comma-separated tags e.g. 'event,2024,tokyo'", max_length=200)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_items', to='sites_config.country')),
            ],
            options={
                'verbose_name': 'Gallery Item',
                'verbose_name_plural': 'Gallery Items',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
